import type { Locale } from "./i18n";

const en = {
  settings: "Cooking display",
  textSize: "Text size",
  normalText: "100%",
  largeText: "115%",
  largestText: "130%",
  contrastOn: "High contrast",
  contrastOff: "Standard contrast",
  focusOn: "Focus on current task",
  focusOff: "Exit focus mode",
  timers: "Timers",
  noTimers: "Timers start automatically with timed steps.",
  running: "Running",
  paused: "Paused",
  completed: "Complete",
  timerPause: "Pause timer",
  timerResume: "Resume timer",
  timerDone: "Mark timer done",
  notificationEnable: "Enable notifications",
  notificationGranted: "Notifications enabled",
  notificationDenied: "Notifications are blocked; in-app sound stays active.",
  notificationUnsupported: "System notifications are unavailable; in-app sound stays active.",
  wakeEnable: "Keep screen awake",
  wakeActive: "Screen will stay awake",
  wakeUnsupported: "Screen wake lock is unavailable on this device.",
  undo: "Undo completion",
  undoAvailable: "Completion pending. Undo is available for five seconds.",
  undoCancelled: "Completion cancelled.",
  undoCommitted: "Step completion saved.",
  completing: "Saving completion…",
  replanTitle: "Something changed?",
  replanDescription: "Record the kitchen fact first. PEAR changes only future affected steps after your approval.",
  factType: "What changed",
  substitution: "Ingredient substitution",
  delay: "Delay",
  equipment: "Equipment change",
  doneness: "Doneness update",
  recipe: "Recipe",
  original: "Original ingredient",
  replacement: "Replacement ingredient",
  delayMinutes: "Delay in minutes",
  reason: "Reason",
  equipmentName: "Equipment",
  equipmentAction: "Equipment status",
  removed: "Unavailable",
  failed: "Failed",
  added: "Available again",
  donenessNote: "Doneness note",
  proposeReplan: "Review affected steps",
  proposing: "Assessing change…",
  replanPending: "Plan change needs approval",
  replanApplied: "Plan change applied. Cooking remains paused until you resume.",
  replanFailed: "Plan change failed",
  affectedSteps: "Affected future steps",
  noAffectedSteps: "No future steps need to change.",
  confirmReplan: "Pause and apply this change",
  resumeCooking: "Resume cooking",
  replanRetry: "Retry assessment",
  feedbackTitle: "How did cooking go?",
  feedbackDescription: "Your timing helps personalize future estimates.",
  rating: "Rating",
  difficulty: "Difficulty",
  easy: "Easier than expected",
  expected: "As expected",
  hard: "Harder than expected",
  actualMinutes: "Actual minutes",
  notes: "Notes",
  submitFeedback: "Save feedback",
  feedbackSaved: "Feedback saved",
  feedbackError: "Feedback could not be saved.",
  voicePermissionPrompt: "Microphone permission will be requested when you start voice guidance.",
  voicePermissionDenied: "Microphone access is blocked. Allow it in browser settings, then retry.",
  voiceInterrupted: "Voice was interrupted. Cooking continues from the authoritative plan.",
  voiceIndependent: "Disconnecting voice does not pause timers or cooking.",
  voiceRetry: "Reconnect voice",
  resumeError: "Could not resume all paused work. Refresh the authoritative state and retry.",
  operationError: "The action failed. Refresh the current state and retry.",
  refresh: "Refresh state",
  minutesShort: "min",
} as const;

const ja: { [K in keyof typeof en]: string } = {
  settings: "調理画面の設定",
  textSize: "文字サイズ",
  normalText: "100%",
  largeText: "115%",
  largestText: "130%",
  contrastOn: "ハイコントラスト",
  contrastOff: "標準コントラスト",
  focusOn: "いまの作業に集中",
  focusOff: "集中表示を終了",
  timers: "タイマー",
  noTimers: "時間のある工程を開始するとタイマーも自動で始まります。",
  running: "計測中",
  paused: "一時停止",
  completed: "完了",
  timerPause: "タイマーを一時停止",
  timerResume: "タイマーを再開",
  timerDone: "タイマーを完了",
  notificationEnable: "通知を有効にする",
  notificationGranted: "通知は有効です",
  notificationDenied: "通知はブロックされています。画面内の音は鳴ります。",
  notificationUnsupported: "端末通知は利用できません。画面内の音は鳴ります。",
  wakeEnable: "画面を点灯したままにする",
  wakeActive: "画面を点灯したままにします",
  wakeUnsupported: "この端末では画面点灯を維持できません。",
  undo: "完了を取り消す",
  undoAvailable: "完了は5秒後に保存されます。今なら取り消せます。",
  undoCancelled: "完了を取り消しました。",
  undoCommitted: "工程の完了を保存しました。",
  completing: "完了を保存中…",
  replanTitle: "状況が変わりましたか？",
  replanDescription: "先にキッチンの事実を記録します。承認後、影響する未来の工程だけを変更します。",
  factType: "変わったこと",
  substitution: "食材の代替",
  delay: "遅れ",
  equipment: "器具の変更",
  doneness: "火の通り",
  recipe: "料理",
  original: "元の食材",
  replacement: "代わりの食材",
  delayMinutes: "遅れ（分）",
  reason: "理由",
  equipmentName: "器具",
  equipmentAction: "器具の状態",
  removed: "使用できない",
  failed: "故障",
  added: "再び使用できる",
  donenessNote: "火の通りについて",
  proposeReplan: "影響する工程を確認",
  proposing: "変更の影響を確認中…",
  replanPending: "調理順の変更に承認が必要です",
  replanApplied: "変更を反映しました。再開するまで調理は一時停止のままです。",
  replanFailed: "調理順を変更できませんでした",
  affectedSteps: "影響する未来の工程",
  noAffectedSteps: "変更が必要な未来の工程はありません。",
  confirmReplan: "一時停止して変更を反映",
  resumeCooking: "調理を再開",
  replanRetry: "影響をもう一度確認",
  feedbackTitle: "調理はいかがでしたか？",
  feedbackDescription: "実際の時間を次回の見積もりに反映します。",
  rating: "評価",
  difficulty: "難しさ",
  easy: "想定より簡単",
  expected: "想定どおり",
  hard: "想定より難しい",
  actualMinutes: "実際にかかった分数",
  notes: "メモ",
  submitFeedback: "感想を保存",
  feedbackSaved: "感想を保存しました",
  feedbackError: "感想を保存できませんでした。",
  voicePermissionPrompt: "音声ガイドを始めるときにマイクの許可を確認します。",
  voicePermissionDenied: "マイクがブロックされています。ブラウザ設定で許可してから再接続してください。",
  voiceInterrupted: "音声が中断しました。調理は現在の調理順のまま続いています。",
  voiceIndependent: "音声を終了してもタイマーや調理は一時停止しません。",
  voiceRetry: "音声を再接続",
  resumeError: "一時停止した作業をすべて再開できませんでした。最新状態を取得して再試行してください。",
  operationError: "操作に失敗しました。最新状態を取得して再試行してください。",
  refresh: "最新状態を取得",
  minutesShort: "分",
};

type ExecutionCopy = { [K in keyof typeof en]: string };

export const executionCopy: Record<Locale, ExecutionCopy> = { en, ja };
